### ISSUE TITLE
fastjson版本错误

### ISSUE THREAD

**Issue by peter-wang-wsl** [open-dingtalk/h5app-corp-quickstart#1]
根目录pom.xml中引用了maven库中不存在的fastjson版本1.2.65，当前开放最新版本1.2.62。
没人使用过这个demo吗？

**Comment by chnyx** [comment]
改成1.2.62可以用吗

**Comment by peter-wang-wsl** [comment]
@chnyx 应该是可以，我maven下载1.2.62好像也失败，后来手动下载拷贝到.m2的

**Comment by journeylee** [comment]
@chnyx 可以使用1.2.62，项目pom.xml中错误引用已修正。
