### ISSUE TITLE
我在使用mvn install时出现以下错误

### ISSUE THREAD

**Issue by ktt711** [open-dingtalk/h5app-corp-quickstart#2]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.dingtalk:h5app-corp-quickstart:1.0.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.6.RELEASE from/to repo1 (http://repo1.maven.org/maven2/): Transfer failed for http://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.0.6.RELEASE/spring-boot-starter-parent-2.0.6.RELEASE.pom 501 HTTPS Required and 'parent.relativePath' points at wrong local POM @ line 17, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.dingtalk:h5app-corp-quickstart:1.0.0-SNAPSHOT (E:\eeproject\h5app-corp-quickstart\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.dingtalk:h5app-corp-quickstart:1.0.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.6.RELEASE from/to repo1 (http://repo1.maven.org/maven2/): Transfer failed for http://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.0.6.RELEASE/spring-boot-starter-parent-2.0.6.RELEASE.pom 501 HTTPS Required and 'parent.relativePath' points at wrong local POM @ line 17, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by journeylee** [comment]
@ktt711 maven中心仓库不再支持纯http访问，需要设置为https域名，请检查您的 .m2/settings.xml 配置
